title: Prueba Learning Lab
description: Curso de Prueba
template:
  repo: prueba-learning-lab-template
  name: prueba-learning-lab
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
  - type: createPullRequest
  - type: createPullRequestComment
  - type: createReview
  - type: createStatus
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
  - title: New step
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
      - type: createReview
